# Dynamic Opentrons OT-2 Protocol Generator
# Generated by Broad-Spectrum Biotech Engine

def generate_ot2_script(peptide_sequence: str, rmsd_value: float, output_filename: str = "src/generated_ot2_protocol.py"):
    """
    Generates a production-ready Opentrons OT-2 serial dilution protocol
    for a given lead peptide candidate.
    """
    protocol_code = f"""# Auto-Generated OT-2 Protocol
# Lead Candidate: {peptide_sequence}
# Final RMSD Plateau: {rmsd_value:.2f} Å

from opentrons import protocol_api

metadata = {{
    'protocolName': 'AMP Serial Dilution - {peptide_sequence}',
    'author': 'Sufyan Vohra / AMP Engine',
    'apiLevel': '2.20'
}}

def run(protocol: protocol_api.ProtocolContext):
    tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', 3)
    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 2)
    reservoir = protocol.load_labware('usascientific_12_reservoir_22ml', 1)
    
    pipette = protocol.load_instrument('p300_single_gen2', mount='left', tip_racks=[tiprack])
    
    # 1. Transfer stock peptide solution ({peptide_sequence}) to Column 1
    pipette.pick_up_tip()
    pipette.transfer(100, reservoir.wells()[0], plate.columns()[0], new_tip='never')
    
    # 2. Perform 1:2 serial dilution across 8 columns for MIC testing
    for i in range(7):
        pipette.transfer(50, plate.columns()[i], plate.columns()[i+1], mix_after=(3, 50), new_tip='never')
        
    pipette.drop_tip()
"""
    with open(output_filename, "w") as f:
        f.write(protocol_code)
    print(f"[+] Dynamic OT-2 protocol successfully written to {output_filename}")

if __name__ == "__main__":
    # Test generation with lead candidate
    generate_ot2_script("IRLFWRWWRKRLFWWIVR", 3.39)
